dir : 'models/hsi/dense_net'

num_classes : 98
fold: 4
BATCH_SIZE : 64
lr : 0.00000744

in_channels : 152
weight_decay : 0.000003
ckpt_file_name : '{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'hsi_densenet'
H : 40
W : 24
C : 152
