dir : 'models/hsi/dense_net'

num_classes : 96

BATCH_SIZE : 64
lr : 0.00000444

in_channels : 152
weight_decay : 0.00001
ckpt_file_name : 'dense_net--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'hsi_dense_net'
H : 40
W : 24
C : 152
