dir : 'models/hsi/dense_net'

num_classes : 98

BATCH_SIZE : 64
lr : 0.00000744

in_channels : 168
weight_decay : 0.000003
ckpt_file_name : 'dense_net--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'hsi_dense_net'
H : 40
W : 24
C : 168
