dir : 'models/hsi/xception'

num_classes : 96

BATCH_SIZE : 50
lr : 0.0000144

in_channels : 152
weight_decay : 0.000003
ckpt_file_name : 'xception--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'hsi_xception'
