dir : 'models/hsi/xception'

num_classes : 107

BATCH_SIZE : 64
lr : 0.0001

in_channels : 168
weight_decay : 0.00001
ckpt_file_name : 'xception--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'hsi_xception'
