dir : 'models/rgb/mobileNet'

num_classes : 96

BATCH_SIZE : 32
lr : 0.00001
weight_decay : 0.0001
ckpt_file_name : 'mnet--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'rgb_mobile_net'
C : 3
H : 247
W : 120