dir : 'models/rgb/densenet'

num_classes : 98

BATCH_SIZE : 128
lr : 0.000007
weight_decay : 0.00009
ckpt_file_name : 'dnet--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'rgb_denseNet_net'
C : 3
H : 247
W : 120